$(call lib,../../src/libmorphodita):
	$(MAKE) -C $(dir $@) $(notdir $@)

$(call lib,../../src/libmorphodita.dyn):
	$(MAKE) -C $(dir $@) $(notdir $@)

.PHONY: veryclean
veryclean: clean
	$(MAKE) -C ../../src clean
