# obj names
obj = $(patsubst %,.objs/%.o,$(1))
dynobj = $(patsubst %,.objs/%.dyn.o,$(1))
libobj = $(subst /$(1)_utils_,/utils_utils_,$(subst .objs_,.objs/$(1)_,$(subst /,_,$(2))))

# dependencies
dep = $(patsubst %, .objs/%.dep, $(1))
HEADERS := $(wildcard *.h */*.h)
DEPENDS := $(call dep, $(basename $(wildcard *.cpp */*.cpp)))
$(call dep, %): %.cpp $(HEADERS)
	@mkdir -p $(@D)
	@$(CXX) $< $(C_FLAGS) -MM -MT $(@:.dep=.o) -MT $(@:.dep=.dyn.o) -o $@
-include $(DEPENDS)

# compilation - static object
$(call obj, %) : %.cpp
	@mkdir -p $(@D)
	$(CXX) $< -c -o $@ $(C_FLAGS)

# compilation - dynamic object
$(call dynobj, %) : %.cpp
	@mkdir -p $(@D)
	$(CXX) $< -c -o $@ $(DYN_C_FLAGS)
