# obj names
obj = $(patsubst %,.objs/%.o,$(1))
dynobj = $(patsubst %,.objs/%.dyn.o,$(1))

# dependencies
DEPENDS := $(foreach cpp,$(wildcard *.cpp */*.cpp),.objs/$(cpp:.cpp=.d) .objs/$(cpp:.cpp=.dyn.d))
-include $(DEPENDS)

# compilation - static object
$(call obj, %) : %.cpp
	@$(call mkdir,$(@D))
	$(CXX) $< -c -MMD -MP -o $@ $(C_FLAGS)

# compilation - dynamic object
$(call dynobj, %) : %.cpp
	@$(call mkdir,$(@D))
	$(CXX) $< -c -MMD -MP -o $@ $(DYN_C_FLAGS)
